# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoWindow(object):
    def setupUi(self, VideoWindow):
        VideoWindow.setObjectName("VideoWindow")
        VideoWindow.resize(902, 684)
        self.centralwidget = QtWidgets.QWidget(VideoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(99, 49, 681, 511))
        self.graphicsView.setObjectName("graphicsView")
        self.openCamButton = QtWidgets.QPushButton(self.centralwidget)
        self.openCamButton.setGeometry(QtCore.QRect(20, 20, 93, 28))
        self.openCamButton.setObjectName("openCamButton")
        VideoWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VideoWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 25))
        self.menubar.setObjectName("menubar")
        VideoWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VideoWindow)
        self.statusbar.setObjectName("statusbar")
        VideoWindow.setStatusBar(self.statusbar)

        self.retranslateUi(VideoWindow)
        QtCore.QMetaObject.connectSlotsByName(VideoWindow)

    def retranslateUi(self, VideoWindow):
        _translate = QtCore.QCoreApplication.translate
        VideoWindow.setWindowTitle(_translate("VideoWindow", "MainWindow"))
        self.openCamButton.setText(_translate("VideoWindow", "PushButton"))
