# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'key_binding_caption.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(412, 630)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.function_code_tab = QtWidgets.QWidget()
        self.function_code_tab.setObjectName("function_code_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.function_code_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.function_code_tab)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.tabWidget.addTab(self.function_code_tab, "")
        self.gesture_code_tab = QtWidgets.QWidget()
        self.gesture_code_tab.setObjectName("gesture_code_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gesture_code_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.gesture_code_tab)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.verticalLayout_3.addWidget(self.groupBox_2, 0, QtCore.Qt.AlignTop)
        self.tabWidget.addTab(self.gesture_code_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "綁定編碼說明"))
        self.groupBox.setTitle(_translate("MainWindow", "功能編碼說明:"))
        self.label.setText(_translate("MainWindow", "0:操作滑鼠模式 \n"
"1:截圖文字辨識\n"
"2:文字翻譯\n"
"3:放大縮小\n"
"4:全螢幕\n"
"5:返回桌面 \n"
"6:下一頁\n"
"7:上一頁\n"
"8:PPT 雷射筆 \n"
"9:複製\n"
"10:貼上\n"
"11:順時針旋轉90度\n"
"12:向上滑\n"
"13:向下滑\n"
"14:螢幕截圖\n"
"15:滑鼠左鍵單點\n"
"16:滑鼠右鍵單點\n"
"17:進入雙手動態模式"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.function_code_tab), _translate("MainWindow", "功能編碼"))
        self.groupBox_2.setTitle(_translate("MainWindow", "手勢編碼說明:"))
        self.label_2.setText(_translate("MainWindow", "0:比五 \n"
"1:握拳\n"
"2:握拳後伸出食指\n"
"3:握拳後食指和拇指尖端連起來 \n"
"4:握拳後中指和拇指尖端連起來\n"
"5:比二\n"
"6:比六\n"
"7:比八 "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gesture_code_tab), _translate("MainWindow", "手勢編碼"))
